### ISSUE TITLE
No need for else block

### ISSUE THREAD

**Issue by SakshiShreya** [learnwebdev123/QuizApp#1]
https://github.com/learnwebdev123/QuizApp/blob/1b47551172c4dd86f5c0449cffb10c3f9547c804/js/script.js#L105-L116

Line 107-110 is same as Line 112-115. You can write the same thing as:

```
if (answer === correctAnswerIndex) { 
  score++; 
}
const correctOption = document.getElementById( 
  `option${correctAnswerIndex}` 
); 
correctOption.parentElement.style.backgroundColor = "lightgreen"; 
```

**Comment by learnwebdev123** [comment]
Hi, Thanks for the correction !!

I Will update this accordingly.
